### ISSUE TITLE
composer deprecation notice

### ISSUE THREAD

**Issue by hello-liang-shan** [grantholle/aliyun-sms-notification-channel#1]
![image](https://user-images.githubusercontent.com/47734732/96398826-5f694800-11ff-11eb-8752-c61b07646b00.png)

mrgoon/aliyun-sms-sdk 好像不维护了

**Comment by grantholle** [comment]
I have sent a PR for the package that is causing this.

**Comment by grantholle** [comment]
Fixed in v1.2, thanks for that pr

**Comment by grantholle** [comment]
And yes I accidentally skipped v1.1... whoops
